# Generated by Django 4.2.5 on 2023-09-25 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField(default='biography')),
                ('birthday', models.DateField(default=datetime.datetime(2023, 9, 25, 16, 6, 46, 666396, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('show_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_2_app.author')),
            ],
        ),
    ]
