# Generated by Django 4.2.5 on 2023-09-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_2_app', '0003_alter_article_category_alter_article_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 14, 59, 30, 772658, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 14, 59, 30, 772069, tzinfo=datetime.timezone.utc)),
        ),
    ]
