# Generated by Django 4.2.5 on 2023-10-02 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_2_app', '0004_alter_article_published_alter_author_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 7, 5, 9, 767273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 7, 5, 9, 766578, tzinfo=datetime.timezone.utc)),
        ),
    ]
